### ISSUE TITLE
Inject files into image?

### ISSUE THREAD

**Issue by nikaro** [chainguard-dev/apko#1020]
Is there a way to inject file into an image? I guess this is doable by building a local apk containing the file but it seems a bit overkill to me.

Something like this would be nice:

```yaml
paths:
  - path: /etc/sudoers.d
    type: directory
    permissions: 0o550
    uid: 0
    gid: 0
  - path: /etc/sudoers.d/nonroot
    type: file
    permissions: 0o550
    uid: 0
    gid: 0
    source: ./sudoers-noonroot
```
