### ISSUE TITLE
Cannot build x86_64 target

### ISSUE THREAD

**Issue by willswire** [chainguard-dev/apko#1060]
I get the following error:

```console
Error: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: could not find package either named so:libc.musl-x86_64.so.1 or that provides so:libc.musl-x86_64.so.1 for clip
2024/03/10 20:29:55 error during command execution: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: could not find package either named so:libc.musl-x86_64.so.1 or that provides so:libc.musl-x86_64.so.1 for clip
```

when running

```console
apko build --debug apko.yaml registry.gitlab.com/willswire/cosmology/clip/publisher:0.2.0 clip.tar -k melange.rsa.pub --arch aarch64,x86_64
```

with the following apko.yaml

```yaml
contents:
  repositories:
    - '@local packages'
  packages:
    - clip@local
accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: nonroot
entrypoint:
  command: /usr/bin/clip
archs:
  - x86_64
  - aarch64
```

**Comment by willswire** [comment]
Just had to update my apko.yaml with musl dependencies:


```yaml
contents:
  repositories:
    - '@local packages'
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
  packages:
    - musl
    - clip@local
  ```
