### ISSUE TITLE
How to include packages from packages registry of gitlab

### ISSUE THREAD

**Issue by mahadevan-karthi-dwp** [chainguard-dev/apko#1079]
Let us say, I push my melange build apks to gitlab registry pacakges 

I want to include 
```
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://gitlab.com/mygroup/my-development/packages/.   <<==== my package registry url 
   packages:
    - my-super-awesome-pacakge 
    
```
    
    
    Or 
    want to send it as command line
    ```

             --keyring-append local-melange.rsa.pub \
            --repository-append https://gitlab.com/mygroup/my-development/packages/ \
            --keyring-append https://gitlab.com/mygroup/my-developmen/my-signing.rsa.pub \
```
            

How do I pass the credential ? 
currently I can login `

apko login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"`
    
  which works. 
  
  will it able to get the packages as well ? 
  
  
  I could not reference it as artifacts path as like 
  
```
   repositories:
    - https://packages.wolfi.dev/os
    - "$CI_PROJECT_DIR/packages"
  packages:
    - wolfi-base
    - ca-certificates-bundle
    - my-secdev-package
```
    
    
    or 
    
```
     - "@local packages"
  packages:
    - wolfi-base
    - ca-certificates-bundle
    - my-secdev-package@local
```
    
 or 
 
```
      - "./packages"
  packages:
    - wolfi-base
    - ca-certificates-bundle
    - my-secdev-package 
```
    
        
     or 
```
 
      - "packages"
  packages:
    - wolfi-base
    - ca-certificates-bundle
    - my-secdev-package 
```
