### ISSUE TITLE
Error "could not find package that provides php-cli in indexes" from the second line packages config

### ISSUE THREAD

**Issue by redhawkeye** [chainguard-dev/apko#1116]
For the first time, I encountered an error like this:

<img width="1379" alt="Screenshot 2024-05-09 at 18 13 50" src="https://github.com/chainguard-dev/apko/assets/90817826/7ddf18c7-6a72-4b12-966f-b1f5a31cccf9">

I had built it previously without any errors.

I am using the APKO version as follows:

<img width="445" alt="Screenshot 2024-05-09 at 18 49 24" src="https://github.com/chainguard-dev/apko/assets/90817826/1f9206b8-f7f6-4c5c-bb59-f07c9bae80e8">

and the configuration is as follows:

```
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - wolfi-base
    - php-cli

cmd: /bin/sh -l

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

archs:
  - x86_64
  - arm64
```

Please let me know if there are any mistakes in my configuration or if there are any new features in the Apko pattern. Thanks
