### ISSUE TITLE
Is it possible to change home dir for user created with apko?

### ISSUE THREAD

**Issue by farcop** [chainguard-dev/apko#1164]
I want to change home dir from /home/user to another one within apko file.

E.g.
```
accounts:
  users:
    - username: myuser
      uid: 10000
      home: /tmp/myuser
```
