### ISSUE TITLE
Error: could not find package either named so:libboost_log-gcc10-mt-x64-1_83.so.1.83.0

### ISSUE THREAD

**Issue by Conor-Behard333** [chainguard-dev/apko#1181]
Hi, I'm using melange and apko to build elasticsearch from source and create a container from the apk output of melange, the melange build works but i get an error when i try building the apko tar

run command: docker run --rm --workdir /work -v ${PWD}:/work cgr.dev/chainguard/apko build apko.yaml es:test es.tar --arch x86_64 -k melange.rsa.pub

error: INFO error during command execution: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: solving "elasticsearch@local" constraint: could not find package either named so:libboost_log-gcc10-mt-x64-1_83.so.1.83.0 or that provides so:libboost_log-gcc10-mt-x64-1_83.so.1.83.0 for elasticsearch

any ideas on how to resolve this?

malange build file:
```YAML
package:
  name: elasticsearch
  version: 0.1.0
  description: elasticsearch
  target-architecture:
    - x86_64

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - openjdk-21
      - gradle-8

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/elastic/elasticsearch.git
      tag: v8.14.1
      expected-commit: 93a57a1a76f556d8aee6a90d1a95b06187501310

  - runs: |
      export JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
      export PATH="$PATH:$JAVA_HOME/bin"
      mkdir -p ${{targets.destdir}}/usr/local/bin
      ./gradlew :distribution:archives:linux-tar:assemble
      cp -r distribution/archives/linux-tar/build/install/elasticsearch-8.14.1-SNAPSHOT ${{targets.destdir}}/usr/local/bin
```
apko build file:
```YAML
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - '@local packages'
  packages:
    - busybox
    - openjdk-21
    - elasticsearch@local

entrypoint:
  command: /bin/sh
```
APKINDEX.json:
```JSON
{
  "Signature": null,
  "Description": "",
  "Packages": [
    {
      "Name": "elasticsearch",
      "Version": "0.1.0-r0",
      "Arch": "x86_64",
      "Description": "elasticsearch",
      "License": "",
      "Origin": "elasticsearch",
      "Maintainer": "",
      "URL": "",
      "Checksum": "0P0snUboL/n31QFVflj3I4lcFvg=",
      "Dependencies": [
        "so:ld-linux-x86-64.so.2",
        "so:libboost_log-gcc10-mt-x64-1_83.so.1.83.0",
        "so:libboost_program_options-gcc10-mt-x64-1_83.so.1.83.0",
        "so:libc.so.6",
        "so:libdl.so.2",
        "so:libgcc_s.so.1",
        "so:libpthread.so.0",
        "so:libstdc++.so.6",
        "so:libz.so.1"
      ],
      "Provides": null,
      "InstallIf": null,
      "Size": 612329919,
      "InstalledSize": 1151110377,
      "ProviderPriority": 0,
      "BuildTime": "1970-01-01T00:00:00Z",
      "BuildDate": 0,
      "RepoCommit": "",
      "Replaces": null,
      "DataHash": "9813e491d8213c7a316126e413e8918b174225619f25da683ea55c8e9b5f6dab"
    }
  ]
}
```
