### ISSUE TITLE
`replaces` doesn't appear to work for symlinks

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/apko#1223]
I was playing around with a demo of custom CA bundles, and noticed that if I tried to overwrite the `cert.pem` symlink that the `replaces` wasn't properly handled (it errors due to the file conflict):
```
unable to install symlink from etc/ssl/cert.pem -> certs/ca-certificates.crt: file already exists
```

My repro case for this is:
```yaml
contents:
  repositories:
  - https://packages.wolfi.dev/os
  - https://apk.mattmoor.dev/mattmoor.io
  keyring:
  - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
  - wolfi-baselayout
  - custom-certificates-bundle=20240315-r2 # r2 fails, r3 passes

archs:
- x86_64
```

The only two APKs under `apk.mattmoor.dev/mattmoor.io` are copied here (not public):
```
gs://artifacts.mattmoor-chainguard.appspot.com/custom-certificates-bundle-20240315-r2.apk
gs://artifacts.mattmoor-chainguard.appspot.com/custom-certificates-bundle-20240315-r3.apk
```
