### ISSUE TITLE
How to authenticate to private APK package repositories?

### ISSUE THREAD

**Issue by kneufeld-pbp** [chainguard-dev/apko#1234]
How does one authenticate to a private package repository for APKs in Artifactory, etc?  

Having  username and password directly in the apko yaml file is a no go for us. 

```yaml
contents: 
   repositories:
     - https://{{USERNAME}}:{{PASSWORD}}@example-company.jfrog.io/artifactory/alpine-local/v3.20/main
   keyring:
     - https://{{USERNAME}}:{{PASSWORD}}@example-company.jfrog.io/artifactory/api/security/keypair/public/repositories/alpine-local
```
references:
- [Alpine Linux Package Manager to work with Artifactory](https://jfrog.com/help/r/jfrog-artifactory-documentation/configure-alpine-linux-package-manager-to-work-with-artifactory)
