### ISSUE TITLE
Support run_as_group

### ISSUE THREAD

**Issue by henrysachs** [chainguard-dev/apko#1386]
Hey There,

to get right into the specifics. I'm currently trying to build an apko image for the gitlab runner helper. More specifically I'm trying to rebuild the ubi image version (see https://gitlab.com/gitlab-org/ci-cd/gitlab-runner-ubi-images/container_registry/1766433) of it because my kubernetes Environment restricts to run as root (but i dont run in openshift). 

When inspecting the original image i see that it runs as user 1001 and group 0

When trying to set these in my apko yaml i wont receive the right group in the end (probably because beeing part of the root group is not good)
So do you have any ideas what I could do against this or how i could run as group 0? 

this is my current apko yaml
```yaml
contents:
  packages:
    - busybox
    - bash
    - ca-certificates
    - dumb-init
    - git
    - git-lfs
    - curl
    - zlib 
    - pcre2 
    - gitlab-runner-helper=17.4.0
    - gitlab-runner-helper-oci-entrypoint=17.4.0
    - gitlab-runner-helper-compat=17.4.0

accounts:
  groups:
    - groupname: gitlab-runner
      gid: 65533
  users:
    - username: gitlab-runner-helper
      uid: 1001
      gid: 0
      shell: /bin/sh
  run-as: gitlab-runner-helper

paths:
  - path: /home
    type: directory
    uid: 1001
    gid: 65533
    permissions: 0o755
  - path: /home/gitlab-runner
    type: directory
    uid: 1001
    gid: 65533
    permissions: 0o755
  - path: /home/gitlab-runner/.gitlab-runner
    type: directory
    uid: 1001
    gid: 65533
    permissions: 0o755
  - path: /cache
    type: directory
    uid: 1001
    gid: 65533
    permissions: 0o777

entrypoint:
  command: "/usr/bin/dumb-init /entrypoint"

cmd: "sh"
```

thanks in advance!
