### ISSUE TITLE
Failure to find key name in .SIGN.RSA256.wolfi-signing.rsa.pub

### ISSUE THREAD

**Issue by juburr** [chainguard-dev/apko#1503]
Yesterday Apko-based builds started failing in our CI pipeline with NO changes on our end.

```
Error: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: error getting repository indexes: failed to find key name in signature file name: .SIGN.RSA256.wolfi-signing.rsa.pub
ℹ️            | error during command execution: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: error getting repository indexes: failed to find key name in signature file name: .SIGN.RSA256.wolfi-signing.rsa.pu
```

I found at least one other public repository where someone reported this exact same issue yesterday, suggesting that this issue may be widespread and not due to a specific change within our project:
https://github.com/imjasonh/kontain.me/issues/221

The relevant sections of our Apko YAML file are:
```
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
```
