### ISSUE TITLE
Issues running cgr.dev/chainguard/apko in Gitlab CI: missing sh in image causes problems

### ISSUE THREAD

**Issue by kastl-ars** [chainguard-dev/apko#1550]
Dear maintainers,

I am trying to use the "official" `cgr.dev/chainguard/apko` image in Gitlab CI, but fail to get it working.

No matter what I try, I cannot get it to succeed, as Gitlab seems to require a shell inside the image. Omitting the `script` tag is not possible. Putting the full build command into the `script` tag fails, even with an empty `entrypoint`.

```
---
stages:
  - build
build_with_apko:
  stage: build
  image:
    name: cgr.dev/chainguard/apko
    entrypoint: [""]
  script:
    - apko version
```

```
---
stages:
  - build
build_with_apko:
  stage: build
  image:
    name: cgr.dev/chainguard/apko
    entrypoint: ["apko", "version"]
  script:
    - "" # or "true" or anything else
```

The error is always something along the lines of `unable to start container process: exec: "sh": executable file not found in $PATH`

I tested with the "old" one from `ghcr.io/chainguard-dev/apko` first, which starts but then fails due to being outdated (some new signatures being used).

Is there a way to do this properly? Or is there an offical image with a shell (other than the restricted latest-dev image)?

Kind Regards,
Johannes
