### ISSUE TITLE
Configurable path mutations to apply to image

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#159]
Some images, such as the nginx one, depend on scripts to run on normal Alpine, but we do not run package scripts in `apko` environment.

As @amouat noticed, this change to stop running scripts in apko 0.2 caused the nginx images to quit working, because the nginx `post-install` script has:

```sh
# This is needed for containers that don't start nginx using init script.
install -d -m 755 -o nginx -g nginx /run/nginx || true

# Install config with the default http server to the new location (since 1.18.0-r13).
if ! [ -e /etc/nginx/http.d/default.conf ]; then
        install -m644 /usr/share/nginx/http-default_server.conf /etc/nginx/http.d/default.conf
fi
```

Accordingly, we probably want the ability to specify a set of path mutations to apply to the final image:

```yaml
paths:
  - path: /run/nginx
    type: directory
    uid: 10000
    gid: 10000
    permissions: 0o755
  - path: /etc/nginx/http.d/default.conf
    type: hardlink
    source: /usr/share/nginx/http-default_server.conf
    uid: 10000
    gid: 10000
    permissions: 0o644
```

I would suggest that we would want to support the following types:

* **directory**: Creates a directory at the location, including parent directories.
* **empty-file**: Creates an empty file at the location, including parent directories.
* **hardlink**: Creates a hardlink at the location to `source`, creates appropriate parent directories.
* **symlink**: Same thing as `hardlink`, but using a symlink instead.

There might be reasons to create FIFOs and device nodes too, but we could handle those later as the need arises.
