### ISSUE TITLE
Derived configurations

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#186]
Writing apko YAML files can be very repetitive.  It would be desirable to be able to have a base configuration that can be inherited from.

Something like:

```yaml
from: github.com/chainguard-dev/apko/baseimages/alpine-edge.yaml@main

contents:
  packages:
    - nano
    - build-base
    - openssl-dev
```

I think `from` should imply a git repository, given the GitOps tooling built around distroless, and kind of feel like go package system.  At least, it makes sense to me.

The settings in the config file would be overlaid on top of the base config.
