### ISSUE TITLE
initializing apk: failed to fixate apk world: exit status 99

### ISSUE THREAD

**Issue by tuananh-finx** [chainguard-dev/apko#229]
i'm trying to build image for arm64. amd64 would build fine but if i add arm64, i will get this 

```
Error: failed to build layer image for "arm64": initializing apk: failed to fixate apk world: exit status 99
2022/06/14 03:50:08 error during command execution: failed to build layer image for "arm64": initializing apk: failed to fixate apk world: exit status 99
```

i have this 
```yaml
contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
    - '@local /github/workspace/packages'
  packages:
    - alpine-baselayout-data
    - ca-certificates-bundle
    - git
    - my-package@local

entrypoint:
  command: /bin/sh

archs:
  - amd64
  - arm64

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532
```

and use this github actions 

```
- uses: chainguard-dev/actions/apko-build@main
  id: apko
  with:
    tag: ghcr.io/${{ github.repository }}:latest
    keyring-append: /github/workspace/melange.rsa.pub
    source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
```

i also add `arm64` and `amd64` to melange-build step
