### ISSUE TITLE
New flags to extract version from specific apk and add as tag

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-dev/apko#403]
Given an apk built with a melange config such as the following:
```
package:
  name: openjdk-17
  version: 17.0.5.8
  epoch: 0
...
```

And an apko manifest containing this package, such as:
```
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - glibc-locale-en
    - busybox
    - bash
    - openjdk-17 # <-------------------
...
```

I propose two new flags to `apko publish` which will open up a specific package's metadata and add the version as an OCI tag. They are the following:
- `--tag-from-package` - package name to extract version from and add as OCI tag
- `--tag-from-package-prefix` - optional prefix to prepend to version specified in  `--tag-from-package`  package

This would allow something like the following:

```
apko publish openjdk-17.apko.yaml r.example.com/myimage:latest \
  --tag-from-package=openjdk-17 --tag-from-package-prefix=openjdk-
```

to autogenerate and write the following additional tags based on the version in the `openjdk-17` apk package:
- `openjdk-17`
- `openjdk-17.0`
- `openjdk-17.0.5`
- `openjdk-17.0.5.8`
- `openjdk-17.0.5.8-r0`

If we were to remove the `--tag-from-package-prefix=openjdk-` flag, we'd end up with something more similar to:
- `17`
- `17.0`
- `17.0.5`
- `17.0.5.8`
- `17.0.5.8-r0`

The stemming (`17.0.5.8` --> `17.0.5` --> `17.0` --> `17`) would be performed based on whether or not the version looks to be semver.

In the case of some other type of version (e.g. date, `20221108`) the resulting extra tags would just be `20221108` and `20221108-rc0`(or `openjdk-20221108` / `openjdk-20221108-rc0`  if using  `--tag-from-package-prefix=openjdk-`)
