### ISSUE TITLE
Feature request: GitHub Action to install and setup APKO

### ISSUE THREAD

**Issue by leongross** [chainguard-dev/apko#428]
It would be great if there was an easy-to-use import for github actions that builds the apko image, which could look like this:

```yaml
- name Build apko image
  uses: chainguard-dev/apko-builder@<hash>
  with:
    path: <image_definition>.yaml
    registry: <some_registry>
    ...
```
