### ISSUE TITLE
native apk implementation: does not handle provides correctly

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#469]
Consider the following config:

```
contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
  packages:
    - openssh-client
```

apko's native apk implementation will fail to resolve the world dependencies, with error `error getting package dependencies: could not find package openssh-client in indexes`.

this is because `openssh-client` is provided by `openssh-client-default` or `openssh-client-krb5`.

In this case, apko should choose `openssh-client-default` as it has the highest `provider_priority`, and all versions are equivalent.
