### ISSUE TITLE
local alias repo appears broken with absolute path etc.

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-dev/apko#549]
With an apko yaml such as:
```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - '@local /work/packages'
  packages:
    - ca-certificates-bundle
    - wolfi-base
    - my-app@local
```

I get the error
```
Error: failed to build layer image: installing apk packages: error getting package dependencies: error getting repository indexes: failed to read repository work/packages/x86_64/APKINDEX.tar.gz: open work/packages/x86_64/APKINDEX.tar.gz: no such file or directory
```

The current working directory in the apko container is `/work`, so modifying the working directory to `/`  appears to be a temporary workaround (or removing the `@local` alias altogether).

However, after doing so, we still get this error:
```
Error: failed to build layer image: installing apk packages: error getting package dependencies: could not find package my-app@local in indexes: %!w(<nil>)
2023/03/06 17:15:04 error during command execution: failed to build layer image: installing apk packages: error getting package dependencies: could not find package my-app@local in indexes: %!w(<nil>)
```

Dropping `@local` from the package name entirely has things working.
