### ISSUE TITLE
local packages not picked up by apko

### ISSUE THREAD

**Issue by Lunarequest** [chainguard-dev/apko#557]
I used melange to build a apk and it created a local package repo. I used the following command to do this
```
docker run --rm --privileged -v "${PWD}":/work \                                                                                                                               
    cgr.dev/chainguard/melange build melange.yaml \
    --arch amd64,aarch64 \
    --repository-append packages --signing-key melange.rsa
```
I tried to use that to try and build an oci image using the following apko.yaml
```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - melange.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - '@local /work/packages'
  packages:
    - ca-certificates-bundle
    - wolfi-base
    - Lunas-blog@local
accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532
entrypoint:
  command: /usr/bin/blog
```
I used this command to generate the oci image
```
docker run -v "$PWD":/work cgr.dev/chainguard/apko build --arch amd64,aarch64 apko.yaml blog:latest blog.tar
``` 
I originally thought this may have been an issue with podman so I installed docker and tried to use it instead, there was no effect so I'm led to believe this is an issue with apko

**Comment by kaniini** [comment]
Have you updated the apko image?  What does `apko version` say?

**Comment by Lunarequest** [comment]
I have updated the image and apko version says
```

**Comment by developer-guy** [comment]
I've got the same problem the error says even if I specify the local packages as `@local /work/packages`:


```shell
Error: failed to build layer image: installing apk packages: error getting package dependencies: error getting repository indexes: failed to read repository @local/x86_64/APKINDEX.tar.gz: open @local/x86_64/APKINDEX.tar.gz: no such file or directory
2023/03/08 14:07:59 error during command execution: failed to build layer image: installing apk packages: error getting package dependencies: error getting repository indexes: failed to read repository @local/x86_64/APKINDEX.tar.gz: open @local/x86_64/APKINDEX.tar.gz: no such file or directory
```

**Comment by satdeveloping** [comment]
@Lunarequest I found a workaround with something like this:
```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - melange.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - /work/packages # List just a reference to the directory
  packages:
    - ca-certificates-bundle
    - wolfi-base
    - Lunas-blog # No @local postFix
accounts:

**Comment by Lunarequest** [comment]
I can confirm the above works ^

**Comment by kaniini** [comment]
@deitch is masked packages working again in our implementation?

**Comment by deitch** [comment]
There was #539 which added it, and then #550 which fixed a single error. It has worked every time I tried it.

If we have a reproduction of an error, I am more than happy to tackle it.

**Comment by deitch** [comment]
Can we close this? I just ran another test, using the below `apko.yaml`, worked like a charm:

```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - "@local /tmp/apk"
  packages:
    - glibc@local
    - wolfi-baselayout@local
```

I copied down the `glibc`, `glibc-locale-posix` and `wolfi-baselayout` apk files to `/tmp/apk`.
