### ISSUE TITLE
FDB format error in /lib/apk/db/installed database

### ISSUE THREAD

**Issue by jamonation** [chainguard-dev/apko#566]
I've run into an issue with an invalid entry in `/lib/apk/db/installed` when adding the `docker` package to an image using `apko build`.

The entry looks like this:

```
P:docker
V:23.0.1-r1
A:x86_64
L:Apache-2.0
T:Pack, ship and run any application as a lightweight container
o:docker
m:Jake Buchholz Göktürk <tomalok@gmail.com>
U:https://www.docker.io/
D:docker-engine docker-cli /bin/sh
p:
c:da73568ccf3415d2fecae6d754cd8414ffbd19f3
i:[]
t:1676483380
S:1611
I:4096
k:0
C:Q1den3dXImY5L6fxYyH8HCjda3XEw=
R:.dummy
```

Running any `apk` command results in an error, e.g.:
```
11e3bb53ff7b:~$ apk stats
ERROR: FDB format error (line 1413, entry 'R')
ERROR: Unable to read database state: database file format error
ERROR: Failed to open apk database: database file format error
```

Looking at the entry, the `R:.dummy` field has no preceding `F:` field(s), the latter of the two being required to populate the `diri` struct in here: https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/337734941831dae9a6aa441e38611c43a5fd72c0/src/database.c#L864-893

What's confusing me is where that `R:` field is coming from. 

Using `alpine:latest` and `docker build` with the following `Dockerfile` results in a good entry:

```
FROM alpine:edge

RUN apk add docker
```

```
C:Q1den3dXImY5L6fxYyH8HCjda3XEw=
P:docker
V:23.0.1-r1
A:x86_64
S:1611
I:4096
T:Pack, ship and run any application as a lightweight container
U:https://www.docker.io/
L:Apache-2.0
o:docker
m:Jake Buchholz Göktürk <tomalok@gmail.com>
t:1676483380
c:da73568ccf3415d2fecae6d754cd8414ffbd19f3
D:docker-engine docker-cli /bin/sh
```

Using the following `apko.yaml` file, I get the bad entry:
```
contents:
  archs:
    - x86_64
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - alpine-baselayout-data
    - apk-tools
    - bash
    - ca-certificates-bundle
    - docker
```

Also notable, running `apk add docker` from within an `apko build` generated image that doesn't contain docker results in the correct database entry.

I've tried using `apko` built from source, and using the cgr.dev image like this and both have the same issue:

```
docker run --rm -v ${PWD}/:/work/ cgr.dev/chainguard/apko build \
  --arch x86_64 apko.yaml academy-base:latest academy-base.tar -k melange.rsa.pub
```
