### ISSUE TITLE
apk: too many levels of symbolic links

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#580]
Consider the following YAML:

```yaml
contents:
    repositories:
        - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
        - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
        - openssl
```

apko will fail to compose a filesystem with:

```
Error: failed to build layer image: installing apk packages: unable to install files for pkg openssl: error creating file usr/share/man/man3/OSSL_trace_enabled.3ossl: open /tmp/apko-1065033492/usr/share/man/man3/OSSL_trace_enabled.3ossl: too many levels of symbolic links
```

And, indeed, somehow OSSL_trace_enabled.3ossl winds up being a symlink to itself, but this isn't the case in the package itself, where it is a proper file.
