### ISSUE TITLE
version sorting is not stable in apko's solver

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#593]
Consider the following apk repository:

```
glibc-2.36-r4
glibc-2.37-r1
glibc-2.37-r2
glibc-2.37-r3
glibc-2.37-r6
```

And the following config:

```
contents:
  repositories:
    - ...
  packages:
    - glibc
```

apko will sometimes choose `2.37-r3`, sometimes choose `2.37-r6`, and sometimes choose `2.36-r4`.  This seems to be due to version sorting being unstable and affected by randomization of golang maps.

cc @deitch

**Comment by deitch** [comment]
I have been trying to recreate this, without much success. I am running the following:

```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - glibc
```

And I consistently get:

```
Mar 23 22:27:57.839 [INFO] [arch:x86_64] installing glibc (2.37-r3)
```

How can I reproduce this?
