### ISSUE TITLE
add support for xattrs in images

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#599]
At the moment, apko fails to pass through xattrs on files in images.  There are two things we probably want to do:

- Pass through xattrs from the APKs themselves
- Allow configuration of xattr mutations, which set new xattrs in the image, e.g.

```yaml
paths:
  - path: /foo/bar
    type: xattr
    key: security.capabilities
    value: ...
```

In tarballs, capabilities are stored as PAX records whose name is prefixed by `SCHILY.xattr.`.

This needs to be handled at the VFS level in a way where Melange's use of the apko tar writer can also provide xattrs to pass through to its own generated tarballs.
