### ISSUE TITLE
conflicts not properly processed

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#687]
consider the following configuration:

```yaml
contents:
    keyring:
        - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
        - https://packages.wolfi.dev/os
    packages:
        - '!py3.10-installer'
        - binutils
        - build-base
        - busybox
        - ca-certificates-bundle
        - py3-gpep517
        - py3-setuptools
        - python3
        - scanelf
        - wget
        - wolfi-base
```

We get the error: `buildImage failed: installing apk packages: error getting package dependencies: could not find package, alias or a package that provides !py3.10-installer in indexes`

But `!py3.10-installer` is a valid dependency for `/etc/apk/world`, and should be taken as a constraint that `py3.10-installer` should never be installed.
