### ISSUE TITLE
Adopt KRM for `apko` file format

### ISSUE THREAD

**Issue by marshall007** [chainguard-dev/apko#725]
Once you have your image configs and build scripts setup, the majority of the work involved in operating a [secure software factory](https://www.chainguard.dev/unchained/secure-your-software-factory-with-melange-and-apko) is config management.

Kubernetes ecosystem has great config management tooling and libraries, which comes as no surprise given that the [Kubernetes Resource Model (KRM)](https://github.com/kubernetes/design-proposals-archive/blob/main/architecture/resource-management.md#declarative-configuration) was designed with that intent.

Virtually all manipulation that needs to take place in the build systems for actual catalogs like [chainguard-images/images](https://github.com/chainguard-images/images) can easily be achieved with off-the-shelf tooling that knows how to manipulate KRM configs.

We can make this a backwards-compatible change to start (make `apiVersion` and `kind` optional) and eventually provide a migration command to rewrite existing configs once we settle on the APIs:

```yaml
# before
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - ca-certificates-bundle
    - wolfi-base

entrypoint:
  command: /bin/sh -l

archs:
- x86_64

annotations:
  org.opencontainers.image.authors: "Chainguard Team https://www.chainguard.dev/"
  org.opencontainers.image.url: https://edu.chainguard.dev/chainguard/chainguard-images/reference/wolfi-base/
  org.opencontainers.image.source: https://github.com/chainguard-images/images/tree/main/images/wolfi-base
```

```yaml
# after
apiVersion: apko.chainguard.dev/v1alpha1
kind: ImageConfig
metadata:
  name: wolfi-base
  annotations:
    org.opencontainers.image.authors: "Chainguard Team https://www.chainguard.dev/"
    org.opencontainers.image.url: https://edu.chainguard.dev/chainguard/chainguard-images/reference/wolfi-base/
    org.opencontainers.image.source: https://github.com/chainguard-images/images/tree/main/images/wolfi-base

contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - ca-certificates-bundle
    - wolfi-base

entrypoint:
  command: /bin/sh -l

archs:
- x86_64
```

Relates to #637
