### ISSUE TITLE
some publish options (eg --package-version-tag) broken in 0.9.0

### ISSUE THREAD

**Issue by joemiller** [chainguard-dev/apko#808]
/I believe something happened between 0.8.0 and 0.9.0 that caused some `apko publish` flags to stop working. The first one I noticed is `--package-version-tag` but I believe others might be impacted such as `--package-version-tag-stem`

I am still digging into the code but right now I am assuming this may have happened in or around the build/publish unification PR https://github.com/chainguard-dev/apko/pull/724 when much of the Opts handling in PublishCmd() changed.

Reproduce:
```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - git
    - git-lfs
    - openssh-client

entrypoint:
  command: /usr/bin/git

work-dir: /home/git

accounts:
  groups:
    - groupname: git
      gid: 65532
  users:
    - username: git
      uid: 65532
      gid: 65532

archs:
  - x86_64
  - aarch64
```

Using both 0.8.0 and 0.9.0, observe that 0.8.0 adds additional tags from the `git` package and 0.9.0 does not:

```console
$ apko publish --debug --package-version-tag=git ./apko.yaml  registry/git:latest --arch host
```

In 0.8.0 this will be seen in the output:
```
❕           | Found version, images will be tagged with 2.41.0-r0
ℹ️            | Returning additional tags [registry/git:2.41.0-r0]
```

I believe other functionality related to `additionalTags` is likely broken too but I have not tested, likely `--package-version-tag-stem`.

I am still digging into the code but since I am unfamiliar with it I am not sure the route to resolve this issue yet. It does seem like this new `additionalTags` var is initialized but never populated  in the PublishCmd func though, and that's where I am starting my dive: https://github.com/chainguard-dev/apko/blob/main/internal/cli/publish.go#L219

~Also, I have noticed the `--sbom` flag to `publish` seems to be broken on 0.8.0 and 0.9.0 as neither of them will produce separate SBOM files on disk (.sbom layers are built and published) and report `WantSBOMS = false` in the debug output.~
