### ISSUE TITLE
How do I publish an actual *image* using `apko publish`, not just the index?

### ISSUE THREAD

**Issue by runiq** [chainguard-dev/apko#826]
Hey,

I'm trying to publish my own Zola image for use on [Codeberg](https://codeberg.org), it looks like this:

```yaml
contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - alpine-baselayout-data
    - busybox
    - zola

entrypoint:
  command: /usr/bin/zola
```

I'm currently building using rootless podman, like this:

```sh
podman run \
  --rm -it --init \
  --security-opt label=disable \
  -v "$XDG_RUNTIME_DIR/containers/auth.json:/root/.docker/config.json" \
  -v "$PWD:/work" \
  cgr.dev/chainguard/apko \
    publish \
    --sbom=false \
    --arch=host \
    zola.yml \
    codeberg.org/runiq/zola:0.17.2
```

While that publishes the index, it doesn't publish the image itself:

```log
ℹ️  x86_64    | finished building filesystem in /tmp/apko-633604221/x86_64
ℹ️  x86_64    | built image layer tarball as /tmp/apko-633604221/image/apko-x86_64.tar.gz
❕ x86_64    | Not generating SBOMs (WantSBOM = false)
ℹ️  x86_64    | building image from layer
ℹ️  x86_64    | OCI layer digest: sha256:57b0f1420ff3510fd14a81d4f81c65bb6bb25795bd7e1feae6761aba7cb52da6
ℹ️  x86_64    | OCI layer diffID: sha256:58a51444a95bb165b6a1386ad7a66d8b633336e5055198d1138473109b9f877e
ℹ️  x86_64    | built index file as /tmp/apko-temp-796979251/index.json
ℹ️            | publish image tag codeberg.org/runiq/zola:0.17.2
ℹ️            | publishing index tag codeberg.org/runiq/zola:0.17.2
codeberg.org/runiq/zola@sha256:46da478fe0cea238520e4856525bc7bcf1ffb657b2e1e9f20eddaa94a3fee175
```

What am I doing wrong here? :thinking:
