### ISSUE TITLE
apko does not appropriate treat duplicate providers as conflicting against each other

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#921]
Consider the following repository:

foo-1.2.3-r0, provides A=4.5.6-r0
bar-4.5.6-r0, provides A=1.2.3-r0
baz-1.2.3-r0, depends on bar

Consider the following world:

foo
baz

apko will generate a solution which installs both `foo` and `bar`, even though only one can be installed at the same time.

apk-tools will correctly generate an error demanding the user explicitly provide a solution where `A` is only provided once.

**Comment by kaniini** [comment]
Assigning @jonjohnsonjr since he's probably the most familiar with the solver at this point

**Comment by jonjohnsonjr** [comment]
It would be great if you had a real example I could validate against.

**Comment by jonjohnsonjr** [comment]
Alright, I've come up with this, which I _think_ exhibits what you're talking about:

```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - libcurl-openssl4
    - curl-rustls

cmd: /bin/sh -l

archs:
- aarch64
```

This fails with:

> failed to build image components: failed to build layer image for "arm64": installing apk packages: installing packages: installing libcurl-openssl4: unable to install files for pkg libcurl-openssl4: writing header for "usr/lib/libcurl.so.4.8.0": conflicting file "usr/lib/libcurl.so.4.8.0" in "libcurl-rustls4" has different origin "curl-rustls" != "curl" in "libcurl-openssl4"

But because `curl-rustls` depends on `libcurl-rustls4` which has:

```
provides = so:libcurl.so.4=4
```

We would want that to fail much earlier than at installation time because this conflicts with `libcurl-openssl4`, which provides the same.
